
- name: install mysql libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
    loop:
    - cryptography
    - pyMySQL

- name: install mysql-server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: start and enable the service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name:  to connect the mysql-server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password}}"
    login_host: mysql.omnamahashivaya.online
  register: mysql_info
  ignore_errors: yes

- name: to print the output
  ansible.builtin.debug:
    msg: "mysql info is:{{ mysql_info }}"

- name: setup mysql root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true  #mysql service check failed


